version: "3.8"

services:
  database:
    image: postgres
    container_name: database_loomi
    restart: always
    network_mode: "host"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: app_loomi
    volumes:
      - .:/usr/app
    network_mode: "host"

volumes:
  pgdata: